#!/usr/bin/env ruby
#^syntax detection

#######################
# Community cookbooks #
#######################
site 'http://community.opscode.com/api/v1'

cookbook 'newrelic', '>= 0.3.6' 
cookbook 'sudo', '>= 1.1.0' 

##################################################
# Community cookbooks with pending pull requests #
##################################################

#cookbook 'ntp',
#  :git => 'https://github.com/mrdavidlaing/ntp',
#  :ref => 'feature-windows-ntp'

####################
# Custom cookbooks #
####################

cookbook 'base', :path => 'cookbooks-sources'
cookbook 'ntp', :path => 'cookbooks-sources'


###########
# Samples #
###########

#cookbook 'user',
#  :git => 'https://github.com/mrdavidlaing/chef-user',
#  :ref => 'add-group-docs'

# cookbook 'rvm',
#   :git => 'https://github.com/fnichol/chef-rvm'

# cookbook 'postgresql',
#   :git => 'https://github.com/findsyou/cookbooks',
#   :ref => 'postgresql-improvements'
