source "https://rubygems.org"

gem "ffi", ">= 1.1.5"
gem "chef", ">= 10.12.0"
gem "rake", ">= 0.9.2.2"
gem "librarian", ">= 0.0.24"
gem "foodcritic", ">= 1.3.0"
if RUBY_PLATFORM=~ /win32/
	gem "ruby-wmi", ">= 0.4.0"
	gem "win32-service", ">= 0.7.2"
end