#!/usr/bin/env rake

desc "Launch new Windows EC2 instances to run integration tests"
task :integration_test_windows do
	stack_name = "Windows2008R2SpotInstance-test-#{Time.new.strftime("%Y%m%dT%H%M%S")}"
	template = "./templates/Windows2008R2SpotInstance.template"

	puts "[WARNING] This takes about 20 min to run, and will start & stop real EC2 instances"

	puts "Validating template: #{template}"
	`./scripts/validate-template.py #{template}`
	puts "Launching Windows cloud stack in eu-west-1 region named #{stack_name}"
	`./scripts/create-stacks.py #{stack_name} #{template} -p KeyName=labs-commander -p NotificationTopic=arn:aws:sns:{REGION}:{ACCOUNT}:as-labs-cityindex-com -p ChefConfigBucketName=cityindex.labs.chef_bootstrap -p ChefEnvironment=ec2-clock-accuracy-research_test -r eu-west --enable_iam`
	
	puts "TODO: Check it all worked..."
end

desc "Launch new Ubuntu EC2 instances to run integration tests"
task :integration_test_ubuntu do
	stack_name = "Ubuntu12-04-test-#{Time.new.strftime("%Y%m%dT%H%M%S")}"
	template = "./templates/Ubuntu1204SpotInstance.template"

	puts "[WARNING] This takes about 20 min to run, and will start & stop real EC2 instances"

	puts "Validating template: #{template}"
	`./scripts/validate-template.py #{template}`
	puts "Launching Ubuntu cloud stack in eu-west-1 region named #{stack_name}"
	`./scripts/create-stacks.py #{stack_name} #{template} -p KeyName=labs-commander -p NotificationTopic=arn:aws:sns:{REGION}:{ACCOUNT}:as-labs-cityindex-com -p ChefConfigBucketName=cityindex.labs.chef_bootstrap -p ChefEnvironment=ec2-clock-accuracy-research_test -r eu-west --enable_iam`

	puts "TODO: Check it all worked..."
end

task :default => 'integration_test_ubuntu'